### ISSUE TITLE
Fehler beim auslesen des Analog Signals

### ISSUE THREAD

**Issue by CaioMarcasMenz** [Lion127/Softwareentwicklungsprojekt-2022#1]
Der Code ist richtig, jedoch bekomme ich immer eine Fehlermeldung, dass es im Iot.Device.Adc kein Objekt "**Mcp3008**" gibt. 

```csharp                                      Usage
using System;
using System.Device.Spi;
using System.Threading;
using Iot.Device.Adc;


var hardwareSpiSettings = new SpiConnectionSettings(0,0);

using var spi = SpiDevice.Create(hardwareSpiSettings);
using (Mcp3008 mcp = new Mcp3008(spi))
{
     while (true)
     {
         double value = mcp.Read(0);
         value = value/ 10.24;
         value = Math.Round(value,2);
         Console.WriteLine($"{value} %");
         Thread.Sleep(500);
     }
}
```

**Comment by lionwaurich** [comment]
Der Code müsste aber eigentlich Funktionieren. 
Ist die Iot.Device.Bindings Datei denn im Programm Ordner?

**Comment by CaioMarcasMenz** [comment]
Die Datei wurde direkt beim erstellen des Programmes hinzugefügt.

**Comment by CaioMarcasMenz** [comment]
Ok es lag an der Datei. Man muss bevor man die Datei einfügt das Programm einmal starten und dann erst ``` dotnet add package Iot.Device.Bindings --version 2.1.0-* ``` einfügen. Wahrscheinlich muss der Raspberry Pi den Pfad erst einmal genutzt haben, damit die Datei dann wirklich dem Programm angehangen wird. Interessanterweise ging es mit der anderen Test Datei ohne Probleme.

**Comment by CaioMarcasMenz** [comment]
Das Problem ist gelöst!
