### ISSUE TITLE
Bild skalieren

### ISSUE THREAD

**Issue by CaioMarcasMenz** [Lion127/Softwareentwicklungsprojekt-2022#2]
Ich wollte mal ein Bild reinstellen aber weiß nicht wie man dieses skalieren kann, es wird zu groß angezeigt.
Die Markdown Syntax im Internet funktioniert auch nicht ```![Name]("URL" "Width=50px")```.

**Comment by lionwaurich** [comment]
Das hat bei mir auch alles nicht funktioniert. Ich habe dann die Bilder davor mit ```Paint``` bearbeitet und in der gewünschten Größe hochgeladen. Wenn du eine Möglichkeit gefunden hast wie es doch geht, kannst du sie mir gerne mitteilen. Sonst einfach mit Paint zurechtschneiden und hochladen

**Comment by CaioMarcasMenz** [comment]
Ah so hätte ich es jetzt auch gemacht, ich habe schon wieder viel zu lange damit verbracht wie man das schön mit Markdown machen kann. Aber naja manchmal sind die trivialsten Lösungen die besten.
