### ISSUE TITLE
Programm Dokumentation

### ISSUE THREAD

**Issue by lionwaurich** [Lion127/Softwareentwicklungsprojekt-2022#3]
Wollen wir das Programm komplett hochladen und dann die Teilschritte (wie wir vorgegangen sind) dokumentieren, oder immer ein Sniped des jeweiligen Abschnittes?

**Comment by CaioMarcasMenz** [comment]
Ich würde das mit den Snipeds machen, da können wir immer die Methoden und dann eine kurze Beschreibung dort mit einfügen, um das Programm besser zu verstehen. Wir haben zwar überall Kommentare stehen aber das ist ja nur die abgespeckte Variante.

**Comment by lionwaurich** [comment]
gut, dann machen wir das lieber so. Wird dann auch übersichtlicher, was genau gemeint ist. Und genau, die Kommentare sind dann nützlich, wenn man das gesamte Programm nachvollziehen will. Für die einzelnen Schritte stimme ich dir zu, da sind Snipeds besser.
